addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "fq3xS0erf0C0PnAqfbg0nyjNlapBVok6cN32+QaUqZkyHMBRYPLj/B0qmF7j1PVDOps+dNvMc10snUAOAts1MQzVgsCVh7QBd7OZf9rhzRBJ7j1tscOQXtVuJuW9xBivFnsNa7lsxRkyVCBAJDzcOuIwgY7345oUhaYD8XWikJIReFvgLTS16yGOlk0l1oZz+JEicVgDnEnLuCQIUwAUVHNGrF6EJ/ZxQ/o4avv9AcZdWFhhr/MnavMYqquUSJ5t6v2O4FZ3BNaBsXtJQA6KRFVzRpuJ/S2gkBG3T5Y1VyArcqoBNonD3O1OvkYWQa80kAgCvr/0XFXZh1UIWrw+UIxaZ6aWlFH1G5o4S3R1an9Xbg8vA+0M8wzRMJHUXP+2jkoSgQnzBM0XfHeUCOmKGBdiyCQepERsN/AJ57qvFjslBZ8XVSUrY//akARDS7iu3fqJoChmXWhgSqgnECw3SVzy3VVBEwLAef6RYemSEjQ/RAeTLCf3mdXO7t4AEJMzZWJBd+itVTvPC7jeCjYoOkI4ORuNBuDspRSB3DbOuZiqrUSKA1KlrZ5zt3gWKUoBLaaVPtkdmvUA314WxxhR1x9TWTLxFE2BGTzazCJYLcDXeGE51awvoDC4CVbE/SfvxvjqWgiepUMIGVZZwZrY/mweV4qMlS0dsCMejdnGKZA="
notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: true

after_success:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
